# TORCH EXAMPLES

In [ ]:
import torch
import time
import numpy as np
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cuda:0


In [ ]:
%%time
start = time.time()
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start
print(f"{elapsed_time: .5f}")

 0.00239
CPU times: user 13 µs, sys: 2 ms, total: 2.02 ms
Wall time: 4.57 ms


In [ ]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time: .5f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time: .5f}")

 0.02434
 0.14924


In [ ]:
probablites = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probablites, num_samples=10, replacement=True)
print(samples)

tensor([1, 0, 1, 1, 1, 0, 1, 1, 0, 1])


In [ ]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [ ]:
# Creates a lower traingle Matrix
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [ ]:
# Creates a upper traingle Matrix
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [ ]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [ ]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [ ]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [ ]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False) # Linear here stands for linear transformation
print(linear(sample))

tensor([  8.1749, -10.6232,  -6.4174], grad_fn=<SqueezeBackward4>)


In [ ]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])

softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [ ]:
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

input_indices = torch.LongTensor([1, 5, 3, 2])
embedded_vectors = embedding(input_indices)

print(embedded_vectors.shape)

torch.Size([4, 100])


In [ ]:
int_64 = torch.randint(1, (3, 2)).float()
#type int64
float_32 = torch.rand(2, 3)
#type float32
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Realised by: [Rudy Tchamba](https://github.com/RudyTchamba/RepoDatascience-MachineLearning.git)